import {randomUUID} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import Decimal from 'decimal.js';
import {z} from 'zod';
import {pool,transaction} from '@/lib/db';
import {AccessError,type User} from '@/shared/access';
import {mfgToday,cash} from './service';
export const ledgerGroups=['Bank Accounts','Cash-in-Hand','Sundry Debtors','Sundry Creditors','Sales Accounts','Purchase Accounts','Direct Expenses','Indirect Expenses','Duties & Taxes','Capital Account','Current Assets','Current Liabilities'] as const;
const id=z.string().uuid(),text=z.string().trim().max(2000),date=z.string().refine(s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Invalid date.');
const money=z.coerce.number().min(0).max(99999999999).refine(v=>new Decimal(v).decimalPlaces()<=2,'Amounts allow at most 2 decimal places.');
const party=z.object({mailing_name:text.default(''),address:text.default(''),state:text.default(''),country:text.default('India'),gst_registration:z.enum(['Unknown','Regular','Composition','Unregistered/Consumer']).default('Unknown'),gstin:z.string().trim().toUpperCase().refine(s=>s===''||/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(s),'Enter a valid 15-character GSTIN.').default(''),place_of_supply:text.default('')});
const details=z.object({delivery_note:text.default(''),dispatch_document:text.default(''),dispatched_through:text.default(''),destination:text.default(''),carrier:text.default(''),lr_number:text.default(''),lr_date:z.union([date,z.literal('')]).default(''),vehicle_no:text.default(''),buyer:party.optional()}).default({delivery_note:'',dispatch_document:'',dispatched_through:'',destination:'',carrier:'',lr_number:'',lr_date:'',vehicle_no:''});
async function audit(db:any,user:User,action:string,key:string,value:unknown){await db.query('INSERT INTO erp_audit(user_id,action,entity_id,details) VALUES($1,$2,$3,$4)',[user.id,action,key,JSON.stringify(value)]);}
export async function saveLedger(user:User,input:unknown){const d=z.object({id:id.optional(),name:text.min(1).max(150),group_name:z.enum(ledgerGroups),customer_id:z.union([id,z.literal('')]).optional(),supplier_id:z.union([id,z.literal('')]).optional(),party_details:party,is_active:z.boolean().default(true)}).parse(input);
 if(d.customer_id&&d.supplier_id)throw new AccessError('Link either a customer or a supplier.');
 if(d.customer_id&&d.group_name!=='Sundry Debtors'||d.supplier_id&&d.group_name!=='Sundry Creditors')throw new AccessError('Customer ledgers belong under Sundry Debtors; supplier ledgers under Sundry Creditors.');
 return transaction(async db=>{await db.query('SELECT pg_advisory_xact_lock(914713)');const key=d.id||randomUUID();if(d.id){const old=(await db.query('SELECT * FROM mfg_ledgers WHERE id=$1',[key])).rows[0];if(!old)throw new AccessError('Ledger not found.',404);if((await db.query('SELECT 1 FROM mfg_vouchers WHERE lines @> $1::jsonb LIMIT 1',[JSON.stringify([{ledger_id:key}])])).rowCount&&(old.group_name!==d.group_name||(old.customer_id||'')!==(d.customer_id||'')||(old.supplier_id||'')!==(d.supplier_id||'')))throw new AccessError('A used ledger’s group and party link are locked.');}
 await db.query('INSERT INTO mfg_ledgers(id,name,group_name,customer_id,supplier_id,party_details,is_active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET name=$2,group_name=$3,customer_id=$4,supplier_id=$5,party_details=$6,is_active=$7',[key,d.name,d.group_name,d.customer_id||null,d.supplier_id||null,JSON.stringify(d.party_details),d.is_active,user.id]);await audit(db,user,'MFG_LEDGER_SAVE',key,d);return {id:key};});
}
const voucherSchema=z.object({id,type:z.enum(['Payment','Receipt','Contra','Journal','Purchase','Sales']),date,narration:text.min(3),reference:text.default(''),lines:z.array(z.object({ledger_id:id,debit:money,credit:money})).min(2).max(100),source_invoice_id:id.optional(),reverses_id:id.optional(),details});
export async function postVoucher(user:User,input:unknown){const d=voucherSchema.parse(input);if(d.date>mfgToday())throw new AccessError('Future vouchers cannot be posted.');
 if(new Set(d.lines.map(l=>l.ledger_id)).size!==d.lines.length)throw new AccessError('Use one line per ledger.');
 const debit=d.lines.reduce((s,l)=>s.add(l.debit),new Decimal(0)),credit=d.lines.reduce((s,l)=>s.add(l.credit),new Decimal(0));
 if(debit.lte(0)||!debit.eq(credit)||d.lines.some(l=>(l.debit>0)===(l.credit>0)))throw new AccessError('Each line must have either debit or credit, and total debits must equal total credits.');
 return transaction(async db=>{await db.query('SELECT pg_advisory_xact_lock(914713)');const existing=(await db.query('SELECT * FROM mfg_vouchers WHERE id=$1',[d.id])).rows[0];if(existing){if(!isDeepStrictEqual(existing.request_snapshot,d))throw new AccessError('Submission ID already used for a different voucher.',409);return {id:d.id,repeated:true};}
 const settings=(await db.query('SELECT * FROM mfg_accounting_settings WHERE id=1')).rows[0];if(!settings?.company_name)throw new AccessError('Set the accounting company and opening date first.');if(d.date<settings.financial_year_start||settings.closed_through&&d.date<=settings.closed_through)throw new AccessError('Voucher date is outside the open accounting period.');
 const lines:Record<string,any>[]=[];for(const l of d.lines){const ledger=(await db.query('SELECT * FROM mfg_ledgers WHERE id=$1 AND is_active',[l.ledger_id])).rows[0];if(!ledger)throw new AccessError('Choose active ledgers.');lines.push({...l,debit:cash(l.debit),credit:cash(l.credit),name:ledger.name,group_name:ledger.group_name,customer_id:ledger.customer_id,party_details:ledger.party_details});}
 const bank=(l:typeof lines[number])=>['Bank Accounts','Cash-in-Hand'].includes(l.group_name);
 if(d.type==='Payment'&&(!lines.some(l=>bank(l)&&Number(l.credit)>0)||lines.some(l=>bank(l)&&Number(l.debit)>0)))throw new AccessError('Payment must credit a cash/bank ledger. Use Contra for bank transfers.');
 if(d.type==='Receipt'&&(!lines.some(l=>bank(l)&&Number(l.debit)>0)||lines.some(l=>bank(l)&&Number(l.credit)>0)))throw new AccessError('Receipt must debit a cash/bank ledger. Use Contra for bank transfers.');
 if(d.type==='Contra'&&!lines.every(bank))throw new AccessError('Contra transfers use only bank and cash ledgers.');
 if(d.type==='Sales'&&!lines.some(l=>l.group_name==='Sales Accounts'&&Number(l.credit)>0))throw new AccessError('Sales must credit a sales ledger.');
 if(d.type==='Purchase'&&!lines.some(l=>l.group_name==='Purchase Accounts'&&Number(l.debit)>0))throw new AccessError('Purchase must debit a purchase ledger.');
 if(d.reverses_id){const original=(await db.query('SELECT * FROM mfg_vouchers WHERE id=$1',[d.reverses_id])).rows[0];if(!original||original.reverses_id||d.type!=='Journal'||d.source_invoice_id||d.date<original.date)throw new AccessError('Invalid reversal. Use a journal dated on or after the original voucher.');if(original.lines.length!==lines.length||!original.lines.every((o:any)=>lines.some(l=>l.ledger_id===o.ledger_id&&new Decimal(l.debit).eq(o.credit)&&new Decimal(l.credit).eq(o.debit))))throw new AccessError('A reversal must exactly reverse every original line.');}
 if(d.source_invoice_id){const invoice=(await db.query('SELECT * FROM mfg_sales_invoices WHERE id=$1',[d.source_invoice_id])).rows[0];if(!invoice||d.type!=='Sales'||d.reverses_id||d.date!==invoice.date||!debit.eq(invoice.grand_total))throw new AccessError('Linked sales voucher must use the final invoice date and exact total.');const customers=lines.filter(l=>Number(l.debit)>0);if(customers.length!==1||customers[0].customer_id!==invoice.customer_id||customers[0].group_name!=='Sundry Debtors')throw new AccessError('Debit the ledger linked to this invoice’s customer.');const sales=lines.filter(l=>l.group_name==='Sales Accounts').reduce((s,l)=>s.add(l.credit).sub(l.debit),new Decimal(0));const tax=lines.filter(l=>l.group_name==='Duties & Taxes').reduce((s,l)=>s.add(l.credit).sub(l.debit),new Decimal(0));if(!sales.eq(invoice.subtotal)||!tax.eq(invoice.gst_amount)||lines.some(l=>Number(l.credit)>0&&!['Sales Accounts','Duties & Taxes'].includes(l.group_name)))throw new AccessError('Sales and tax credits must match the invoice subtotal and GST exactly.');}
 const n=(await db.query("SELECT nextval('mfg_voucher_number') n")).rows[0].n,number=`MV/${d.date.slice(0,4)}/${String(n).padStart(6,'0')}`;
 await db.query('INSERT INTO mfg_vouchers(id,voucher_no,type,date,narration,reference,lines,total,source_invoice_id,reverses_id,details,request_snapshot,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[d.id,number,d.type,d.date,d.narration,d.reference,JSON.stringify(lines),debit.toFixed(2),d.source_invoice_id||null,d.reverses_id||null,JSON.stringify(d.details),JSON.stringify(d),user.id]);await audit(db,user,'MFG_VOUCHER_POSTED',d.id,{number,type:d.type,total:debit.toFixed(2)});return {id:d.id,number};});
}
export async function saveAccountingSettings(user:User,input:unknown){if(user.role!=='OWNER')throw new AccessError('Only the owner can change accounting settings.',403);const d=z.object({company_name:text.min(1),financial_year_start:date,closed_through:z.union([date,z.literal('')])}).parse(input);if(d.closed_through&&d.closed_through>mfgToday())throw new AccessError('Cannot close a future period.');return transaction(async db=>{await db.query('SELECT pg_advisory_xact_lock(914713)');const old=(await db.query('SELECT * FROM mfg_accounting_settings WHERE id=1')).rows[0];if(old.closed_through&&(!d.closed_through||d.closed_through<old.closed_through))throw new AccessError('A closed period cannot be reopened here.');if((await db.query('SELECT 1 FROM mfg_vouchers LIMIT 1')).rowCount&&(old.company_name!==d.company_name||old.financial_year_start!==d.financial_year_start))throw new AccessError('Company mapping and opening date are locked after the first voucher.');await db.query('UPDATE mfg_accounting_settings SET company_name=$1,financial_year_start=$2,closed_through=$3,updated_by=$4,updated_at=now() WHERE id=1',[d.company_name,d.financial_year_start,d.closed_through||null,user.id]);await audit(db,user,'MFG_ACCOUNTING_SETTINGS','1',d);return {ok:true};});}
export async function accountingState(){const [ledgers,vouchers,settings,invoices,customers,suppliers]=await Promise.all([pool.query('SELECT * FROM mfg_ledgers ORDER BY name'),pool.query('SELECT * FROM mfg_vouchers ORDER BY date DESC,created_at DESC'),pool.query('SELECT * FROM mfg_accounting_settings WHERE id=1'),pool.query('SELECT id,invoice_no,date,customer_id,subtotal,gst_amount,grand_total,snapshot FROM mfg_sales_invoices ORDER BY date DESC'),pool.query('SELECT id,name FROM mfg_customers ORDER BY name'),pool.query('SELECT id,name FROM mfg_suppliers ORDER BY name')]);return {ledgers:ledgers.rows,vouchers:vouchers.rows,settings:settings.rows[0],invoices:invoices.rows,customers:customers.rows,suppliers:suppliers.rows,today:mfgToday()};}
