'use client';
import SearchSelect from './search-select';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import Decimal from 'decimal.js';
import {Factory,LayoutDashboard,Users,Package,ShoppingCart,Truck,ClipboardCheck,Boxes,FileText,Plus,Search,X,Download,ArrowRight,ArrowDownLeft,Pencil,Trash2,AlertTriangle,Check,Menu} from 'lucide-react';
import './manufacturing.css';
import {ProductionTable,BomForm,WorkOrderForm,ProductionForm,Requirements} from './production-ui';
type Row=Record<string,any>;
const money=(n:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));
const quantity=(n:unknown)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:3}).format(Number(n||0));
const dateLabel=(date:string)=>new Date(date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const title:Row={boms:'Bills of materials',workorders:'Work orders',production:'Production entries',overview:'Manufacturing overview',suppliers:'Suppliers',raw:'Raw materials',purchase:'Purchase orders',receipts:'Goods receipts',finished:'Finished goods',customers:'Customers',sales:'Sales orders',dispatches:'Dispatch notes',invoices:'Sales invoices',openings:'Opening stock'};
const descriptions:Row={boms:'Versioned recipes for your finished goods.',workorders:'Plan batches and track completed production.',production:'Consume raw materials and record finished output.',overview:'From purchase to stock to sale. Everything in one place.',suppliers:'The partners who supply your raw materials.',raw:'Raw-material balances after receipts and production consumption.',purchase:'Order materials and track what is still to arrive.',receipts:'Record full or partial deliveries against sent purchase orders.',finished:'Your sellable products and available stock.',customers:'Customers for manufactured goods.',sales:'Customer orders, quantities and agreed selling prices.',dispatches:'Send available finished goods against confirmed sales orders.',invoices:'Final sales invoices with their own numbering series.',openings:'A one-time, audited starting balance for each finished good.'};
const nav=[['overview',LayoutDashboard],['suppliers',Users],['raw',Package],['purchase',ShoppingCart],['receipts',ArrowDownLeft],['finished',Boxes],['boms',ClipboardCheck],['workorders',Factory],['production',Package],['customers',Users],['sales',ClipboardCheck],['dispatches',Truck],['invoices',FileText],['openings',Package]] as const;
const masters=['suppliers','customers','raw','finished'];
export async function request(action:string,data?:unknown){const response=await fetch('/api/manufacturing/'+action,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(response.status===401){window.location.assign('/login');throw new Error('Your session expired. Please sign in.');}if(!response.ok)throw new Error(result.error||'Unable to complete this action.');return result;}
function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="m-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Status({value}:{value:string}){return <span className={'m-status '+(value==='DRAFT'?'draft':value==='CANCELLED'?'cancelled':value.startsWith('PARTIALLY')?'partial':'posted')}>{value.replaceAll('_',' ').toLowerCase()}</span>;}
function Empty({text}:{text:string}){return <div className="m-empty"><Package size={30}/><h3>{text}</h3><p>Your saved records will appear here.</p></div>;}
function Dialog({title,children,close}:{title:string;children:ReactNode;close:()=>void}){
 const ref=useRef<HTMLDivElement>(null),closeRef=useRef(close);closeRef.current=close;
 useEffect(()=>{const prior=document.activeElement as HTMLElement;const box=ref.current;box?.querySelector<HTMLElement>('input,select,button')?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'&&box){const nodes=Array.from(box.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]'));if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=overflow;prior?.focus();};},[]);
 return <div className="m-overlay" onClick={close}><div className="m-dialog" ref={ref} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button className="icon-button" type="button" aria-label="Close dialog" onClick={close}><X size={21}/></button></header>{children}</div></div>;
}
function PdfLink({kind,id}:{kind:string;id:string}){return <a className="m-small-button" href={`/api/manufacturing/documents/${kind}/${id}`}><Download size={15}/>PDF</a>;}
function remaining(order:Row,docs:Row[],key:string){const counts=new Map<string,Decimal>();for(const d of docs.filter(d=>d[key]===order.id))for(const l of d.lines)counts.set(l.item_id,(counts.get(l.item_id)||new Decimal(0)).add(l.quantity));return order.lines.map((l:Row)=>({...l,remaining:new Decimal(l.quantity).sub(counts.get(l.item_id)||0).toNumber()}));}
export default function ManufacturingApp(){
 const [data,setData]=useState<Row|null>(null),[tab,setTab]=useState('overview'),[search,setSearch]=useState(''),[modal,setModal]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false);
 async function refresh(){setData(await request('state'));}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 function go(view:string){setTab(view);setSearch('');setMenu(false);}
 async function run(action:string,payload:unknown,message='Saved successfully.') {setBusy(true);setError('');try{await request(action,payload);setNotice(message);setModal(null);try{await refresh();}catch{setError('Your entry was saved, but the list could not refresh. Reload this page before continuing.');}return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 function open(kind:string,record?:Row){setError('');setNotice('');setModal({kind,record});}
 if(!data)return <main className="m-loading"><Factory size={40}/><h2>{error?'Unable to open manufacturing':'Opening manufacturing…'}</h2>{error&&<><p role="alert">{error}</p><button className="primary" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</button></>}</main>;
 const matches=(row:Row)=>Object.values(row).filter(v=>typeof v==='string').join(' ').toLowerCase().includes(search.toLowerCase());
 const addLabels:Row={boms:'New BOM revision',workorders:'New work order',production:'Record production',suppliers:'Add supplier',customers:'Add customer',raw:'Add raw material',finished:'Add finished good',purchase:'New purchase order',sales:'New sales order',receipts:'Record goods receipt',dispatches:'Record dispatch',invoices:'Issue sales invoice',openings:'Record opening stock'};
 return <div className="m-app"><aside className={'m-sidebar '+(menu?'expanded':'')}><div className="m-brand"><span><Factory size={25}/></span><div><strong>Manufacturing</strong><small>JYOTI OPERATIONS</small></div></div><small className="m-nav-label">PURCHASE · STOCK · SALES</small><nav><a className="m-small-button" style={{marginBottom:12,padding:12}} href="/manufacturing/accounting">Accounts &amp; vouchers</a>{nav.map(([key,Icon])=><button key={key} onClick={()=>go(key)} className={tab===key?'active':''}><Icon size={18}/>{title[key]}</button>)}</nav><div className="m-sidebar-note"><span className="live-dot"/> Manufacturing workspace</div></aside><main className="m-main">
  <header className="m-heading"><div><button className="m-mobile-toggle icon-button" onClick={()=>setMenu(!menu)} aria-label="Toggle manufacturing navigation"><Menu/></button><div className="eyebrow">JYOTI ENGINEERING & SCAFFOLD</div><h1>{title[tab]}</h1><p>{descriptions[tab]}</p></div>{tab==='overview'?<button className="primary" onClick={()=>{go('purchase');open('purchase');}}><Plus size={18}/>New purchase order</button>:<button className="primary" onClick={()=>open(tab)}><Plus size={18}/>{addLabels[tab]}</button>}</header>
  {error&&!modal&&<div className="alert error" role="alert"><AlertTriangle size={17}/>{error}</div>}{notice&&<div className="alert success" role="status"><Check size={18}/>{notice}</div>}
  {tab==='overview'?<><section className="m-panel" style={{padding:20,marginBottom:20}}><div className="m-panel-title"><div><h2>Production floor</h2><p>{data.workorders.filter((w:Row)=>['RELEASED','IN_PROGRESS'].includes(w.status)).length} active work orders · {data.production.filter((p:Row)=>p.date===data.today).reduce((n:number,p:Row)=>n+p.quantity,0)} pieces produced today</p></div><button className="text-button" onClick={()=>go('workorders')}>View work orders<ArrowRight size={16}/></button></div></section><Overview data={data} go={go}/></>:<section className="m-panel"><div className="m-toolbar"><div className="m-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${title[tab].toLowerCase()}…`} aria-label="Search records"/></div><span>{data[tab]?.length||0} records</span></div>
   {['boms','workorders','production'].includes(tab)&&<ProductionTable view={tab} data={data} search={search} open={open} run={run} busy={busy}/>}
   {masters.includes(tab)&&<MasterTable kind={tab} rows={data[tab].filter(matches)} edit={r=>open(tab,r)} remove={r=>open('remove',{...r,masterKind:tab})}/>}
   {(tab==='purchase'||tab==='sales')&&<OrderTable kind={tab} rows={data[tab].filter((r:Row)=>matches({...r,party:r.party_snapshot.name}))} open={r=>open('detail',{...r,orderKind:tab})} edit={r=>open(tab,r)} activate={r=>run(`orders/${tab}/activate`,{id:r.id},tab==='purchase'?'Purchase order marked as sent.':'Sales order confirmed.')} busy={busy}/>}
   {(tab==='receipts'||tab==='dispatches')&&<MovementTable kind={tab} rows={data[tab].filter(matches)} data={data}/>}
   {tab==='invoices'&&(data.invoices.length?<div className="m-table"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>GST</th><th>Total</th><th>Status</th><th/></tr></thead><tbody>{data.invoices.filter((r:Row)=>matches({...r,customer:r.snapshot.customer.name})).map((r:Row)=><tr key={r.id}><td><strong>{r.invoice_no}</strong><small>{r.snapshot.order_no}</small></td><td>{r.snapshot.customer.name}</td><td>{dateLabel(r.date)}</td><td>{money(r.gst_amount)}</td><td><strong>{money(r.grand_total)}</strong></td><td><Status value={r.status}/></td><td><PdfLink kind="invoice" id={r.id}/></td></tr>)}</tbody></table></div>:<Empty text="No sales invoices yet"/>)}
   {tab==='openings'&&(data.openings.length?<div className="m-table"><table><thead><tr><th>Finished good</th><th>Date</th><th>Opening quantity</th><th>Audit note</th></tr></thead><tbody>{data.openings.filter(matches).map((r:Row)=><tr key={r.id}><td><strong>{data.finished.find((i:Row)=>i.id===r.finished_good_id)?.name}</strong></td><td>{dateLabel(r.date)}</td><td>{quantity(r.quantity)} pcs</td><td>{r.notes}</td></tr>)}</tbody></table></div>:<Empty text="Record your starting finished-goods stock"/>)}
  </section>}
  <footer className="m-footer"><Factory size={14}/> Jyoti Manufacturing · Purchase to sales</footer>
 </main>
 {modal&&<Dialog title={modal.kind==='workdetail'?'Material requirements':modal.kind==='cancelwork'?'Cancel work order':modal.kind==='detail'?modal.record.po_no||modal.record.so_no:modal.kind==='remove'?'Remove master record':(modal.record?'Edit ':'')+(addLabels[modal.kind]||modal.kind)} close={()=>{if(!busy){setModal(null);setError('');}}}>
  {error&&<div className="alert error" role="alert">{error}</div>}
  {modal.kind==='boms'&&<BomForm data={data} record={modal.record} busy={busy} save={d=>run('boms',d,'BOM revision saved. Existing work orders keep their original recipe.')}/>}
  {modal.kind==='workorders'&&<WorkOrderForm data={data} busy={busy} save={d=>run('workorders',d,'Work order created. Release it when ready.')}/>}
  {modal.kind==='production'&&<ProductionForm data={data} record={modal.record} busy={busy} save={d=>run('production',d,'Production posted. Raw materials consumed and finished stock updated.')}/>}
  {modal.kind==='workdetail'&&<><h3>{modal.record.work_order_no} · {modal.record.product_name}</h3><p className="m-help">BOM v{modal.record.bom_snapshot.revision} · Requirements for the remaining {modal.record.quantity-modal.record.completed_quantity} pieces. Stock is not reserved.</p><Requirements lines={modal.record.bom_snapshot.lines} count={modal.record.quantity-modal.record.completed_quantity} data={data}/></>}
  {modal.kind==='cancelwork'&&<><p>Cancel work order <strong>{modal.record.work_order_no}</strong>? No stock has been consumed.</p><div className="m-form-actions"><button className="secondary" onClick={()=>setModal(null)}>Keep work order</button><button className="primary" disabled={busy} onClick={()=>run('workorders/transition',{id:modal.record.id,action:'cancel'},'Work order cancelled.')}>Cancel work order</button></div></>}
  {masters.includes(modal.kind)&&<MasterForm kind={modal.kind} record={modal.record} busy={busy} save={d=>run(`masters/${modal.kind}`,d)}/>}
  {(modal.kind==='purchase'||modal.kind==='sales')&&<OrderForm kind={modal.kind} data={data} record={modal.record} busy={busy} save={d=>run(`orders/${modal.kind}`,d,'Order saved as a draft.')}/>}
  {(modal.kind==='receipts'||modal.kind==='dispatches')&&<MovementForm kind={modal.kind} data={data} busy={busy} save={d=>run(`movements/${modal.kind==='receipts'?'purchase':'sales'}`,d,'Stock movement posted and order status updated.')}/>}
  {modal.kind==='openings'&&<OpeningForm data={data} busy={busy} save={d=>run('opening-stock',d,'Opening stock recorded with its audit note.')}/>}
  {modal.kind==='invoices'&&<InvoiceForm data={data} busy={busy} save={d=>run('invoices',d,'Final sales invoice issued. Download its PDF from Sales invoices.')}/>}
  {modal.kind==='remove'&&<><p>Remove <strong>{modal.record.name}</strong>? If this record has existing orders or stock history, it will be archived so the history stays intact.</p><div className="m-form-actions"><button className="secondary" onClick={()=>setModal(null)}>Keep record</button><button className="primary" disabled={busy} onClick={()=>run(`masters/${modal.record.masterKind}/remove`,{id:modal.record.id},'Record removed or archived.')}>Remove / archive</button></div></>}
  {modal.kind==='detail'&&<OrderDetail data={data} order={modal.record} busy={busy} cancel={()=>run(`orders/${modal.record.orderKind}/cancel`,{id:modal.record.id},'Order cancelled.')}/>}
 </Dialog>}
 </div>;
}
function Overview({data,go}:{data:Row;go:(s:string)=>void}){
 const openPO=data.purchase.filter((p:Row)=>['SENT','PARTIALLY_RECEIVED'].includes(p.status)),openSO=data.sales.filter((p:Row)=>['CONFIRMED','PARTIALLY_DISPATCHED'].includes(p.status)),low=data.raw.filter((r:Row)=>r.is_active&&Number(r.current_stock_qty)<=Number(r.low_stock_qty)),monthly=data.invoices.filter((i:Row)=>i.date.slice(0,7)===data.today.slice(0,7)).reduce((s:number,i:Row)=>s+Number(i.grand_total),0);
 return <><div className="m-stats">{[['Awaiting material',openPO.length,'Open purchase orders',ShoppingCart],['Low-stock materials',low.length,'At or below reorder level',AlertTriangle],['Awaiting dispatch',openSO.length,'Open sales orders',Truck],['This month’s sales',money(monthly),'Final sales invoices',FileText]].map(([label,value,detail,Icon]:any)=><div className="m-stat" key={label}><span>{label}<Icon size={19}/></span><strong>{value}</strong><small>{detail}</small></div>)}</div><div className="m-dashboard-grid"><section className="m-panel"><div className="m-panel-title"><div><h2>Purchase pipeline</h2><p>Track incoming material against your orders</p></div><button className="text-button" onClick={()=>go('purchase')}>View orders<ArrowRight size={16}/></button></div>{openPO.length?<div className="m-table"><table><thead><tr><th>Purchase order</th><th>Supplier</th><th>Status</th><th>Value</th></tr></thead><tbody>{openPO.slice(0,5).map((p:Row)=><tr key={p.id}><td><strong>{p.po_no}</strong></td><td>{p.party_snapshot.name}</td><td><Status value={p.status}/></td><td>{money(p.total_amount)}</td></tr>)}</tbody></table></div>:<Empty text="No material awaiting receipt"/>}</section><section className="m-blue-card"><div className="eyebrow">YOUR DAILY WORKFLOW</div><h2>Purchase. Receive.<br/>Sell. Dispatch.</h2><p>Posted receipts and dispatch notes keep your stock balances up to date.</p><button onClick={()=>go('receipts')}>Record a goods receipt<ArrowRight size={18}/></button><div><Check size={16}/> Partial receipts and dispatches</div><div><Check size={16}/> Protected stock balances</div><div><Check size={16}/> Separate sales invoice series</div></section></div><div className="m-dashboard-grid"><section className="m-panel"><div className="m-panel-title"><h2>Material to replenish</h2><button className="text-button" onClick={()=>go('raw')}>View materials</button></div>{low.length?<div className="m-table"><table><thead><tr><th>Raw material</th><th>Available</th><th>Reorder level</th></tr></thead><tbody>{low.slice(0,6).map((r:Row)=><tr key={r.id}><td><strong>{r.name}</strong></td><td><span className="m-status partial">{quantity(r.current_stock_qty)} {r.unit}</span></td><td>{quantity(r.low_stock_qty)} {r.unit}</td></tr>)}</tbody></table></div>:<Empty text="No low-stock alerts"/>}</section><section className="m-panel"><div className="m-panel-title"><h2>Orders ready for your team</h2><button className="text-button" onClick={()=>go('sales')}>View sales</button></div>{openSO.length?<div className="m-order-list">{openSO.slice(0,5).map((s:Row)=><button key={s.id} onClick={()=>go('dispatches')}><span><strong>{s.party_snapshot.name}</strong><small>{s.so_no}</small></span><Status value={s.status}/><ArrowRight size={16}/></button>)}</div>:<Empty text="No sales orders awaiting dispatch"/>}</section></div></>;
}
function MasterTable({kind,rows,edit,remove}:{kind:string;rows:Row[];edit:(r:Row)=>void;remove:(r:Row)=>void}){if(!rows.length)return <Empty text={`No ${title[kind].toLowerCase()} found`}/>;const product=kind==='raw'||kind==='finished';return <div className="m-table"><table><thead><tr><th>Name</th>{product?<><th>Current stock</th><th>{kind==='raw'?'Reorder level':'Sale rate / piece'}</th><th>{kind==='raw'?'Unit':'HSN / Weight'}</th></>:<><th>Contact</th><th>Mobile</th><th>GST number</th></>}<th>Status</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{!product&&<small>{r.address}</small>}</td>{product?<><td><strong>{quantity(r.current_stock_qty)} {r.unit||'pcs'}</strong><small>Read-only stock</small></td><td>{kind==='raw'?quantity(r.low_stock_qty):money(r.sale_rate)}</td><td>{kind==='raw'?r.unit:<>{r.hsn_code||'—'}<small>{quantity(r.unit_weight)} kg / pc</small></>}</td></>:<><td>{r.contact||'—'}</td><td>{r.mobile||'—'}</td><td>{r.gst_no||'—'}</td></>}<td><Status value={r.is_active?'ACTIVE':'ARCHIVED'}/></td><td><div className="m-row-actions"><button className="icon-button" onClick={()=>edit(r)} aria-label={`Edit ${r.name}`}><Pencil size={16}/></button><button className="icon-button" onClick={()=>remove(r)} aria-label={`Remove ${r.name}`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>;}
function MasterForm({kind,record,busy,save}:{kind:string;record?:Row;busy:boolean;save:(d:Row)=>void}){const party=kind==='suppliers'||kind==='customers';return <form onSubmit={e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));save({...raw,...(record?{id:record.id}:{}),is_active:raw.is_active==='on'});}}><div className="m-form-grid"><div className="m-span"><Field label="Name"><input name="name" required defaultValue={record?.name}/></Field></div>{party?<>{[['contact','Contact person'],['mobile','Mobile'],['gst_no','GST number']].map(([key,label])=><Field key={key} label={label}><input name={key} defaultValue={record?.[key]}/></Field>)}<div className="m-span"><Field label="Address"><textarea name="address" defaultValue={record?.address}/></Field></div></>:kind==='raw'?<><Field label="Unit"><select name="unit" defaultValue={record?.unit||'kg'}><option value="kg">Kilograms (kg)</option><option value="pc">Pieces (pc)</option><option value="mtr">Metres (mtr)</option></select></Field><Field label="Low-stock / reorder level"><input type="number" name="low_stock_qty" min="0" step="0.001" defaultValue={record?.low_stock_qty||0}/></Field></>:<><Field label="HSN code"><input name="hsn_code" defaultValue={record?.hsn_code}/></Field><Field label="Default sale rate (₹ / piece)"><input name="sale_rate" required type="number" min="0" step="0.0001" defaultValue={record?.sale_rate||0}/></Field><Field label="Weight per piece (kg)"><input name="unit_weight" type="number" min="0" step="0.001" defaultValue={record?.unit_weight||0}/></Field></>}<label className="m-check"><input name="is_active" type="checkbox" defaultChecked={record?.is_active??true}/>Active</label></div>{!party&&<p className="m-help">Stock is updated through {kind==='raw'?'goods receipts and production':'opening stock, production and dispatch notes'}, not this form.</p>}<div className="m-form-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form>;}
function OrderTable({kind,rows,open,edit,activate,busy}:{kind:string;rows:Row[];open:(r:Row)=>void;edit:(r:Row)=>void;activate:(r:Row)=>void;busy:boolean}){if(!rows.length)return <Empty text="No orders found"/>;return <div className="m-table"><table><thead><tr><th>Order</th><th>{kind==='purchase'?'Supplier':'Customer'}</th><th>Date</th><th>Status</th><th>Order value</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="text-button" onClick={()=>open(r)}>{r.po_no||r.so_no}</button><small>{r.lines.length} line items</small></td><td>{r.party_snapshot.name}</td><td>{dateLabel(r.date)}</td><td><Status value={r.status}/></td><td><strong>{money(r.total_amount)}</strong></td><td><div className="m-row-actions"><PdfLink kind={kind} id={r.id}/>{r.status==='DRAFT'&&<><button className="icon-button" onClick={()=>edit(r)} aria-label="Edit order"><Pencil size={16}/></button><button className="m-small-button" disabled={busy} onClick={()=>activate(r)}>{kind==='purchase'?'Mark sent':'Confirm'}</button></>}</div></td></tr>)}</tbody></table></div>;}
function OrderForm({kind,data,record,busy,save}:{kind:string;data:Row;record?:Row;busy:boolean;save:(d:Row)=>void}){
 const purchase=kind==='purchase',items=data[purchase?'raw':'finished'].filter((r:Row)=>r.is_active),parties=data[purchase?'suppliers':'customers'].filter((r:Row)=>r.is_active);
 const [party,setParty]=useState(record?.[purchase?'supplier_id':'customer_id']||''),[lines,setLines]=useState<Row[]>(record?.lines.map((l:Row)=>({item_id:l.item_id,quantity:l.quantity,rate:l.rate}))||[{item_id:'',quantity:1,rate:0}]);
 const total=lines.reduce((s,l)=>s.add(new Decimal(l.quantity||0).mul(l.rate||0).toDecimalPlaces(2)),new Decimal(0));
 function update(i:number,patch:Row){setLines(current=>current.map((l,j)=>i===j?{...l,...patch}:l));}
 return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),...(record?{id:record.id}:{}),party_id:party,lines});}}><div className="m-form-grid"><Field label={purchase?'Supplier':'Customer'}><SearchSelect value={party} required onChange={setParty} options={parties}/></Field><Field label="Order date"><input name="date" type="date" required max={data.today} defaultValue={record?.date||data.today}/></Field></div>{!parties.length&&<p className="m-help">Add a {purchase?'supplier':'customer'} in its master first.</p>}<h3 className="m-form-section-title">Order lines</h3>{lines.map((l,i)=><div className="m-line" key={i}><Field label={purchase?'Raw material':'Finished good'}><select value={l.item_id} required onChange={e=>update(i,{item_id:e.target.value,rate:purchase?l.rate:items.find((r:Row)=>r.id===e.target.value)?.sale_rate||0})}><option value="">Select item</option>{items.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Quantity"><input type="number" required min={purchase&&items.find((r:Row)=>r.id===l.item_id)?.unit!=='pc'?'0.001':'1'} step={purchase&&items.find((r:Row)=>r.id===l.item_id)?.unit!=='pc'?'0.001':'1'} value={l.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></Field><Field label="Rate (₹)"><input type="number" required min="0" step="0.0001" value={l.rate} onChange={e=>update(i,{rate:Number(e.target.value)})}/></Field><span className="m-line-value">{money(new Decimal(l.quantity||0).mul(l.rate||0).toString())}</span>{lines.length>1&&<button type="button" className="icon-button" aria-label="Remove line" onClick={()=>setLines(lines.filter((_,j)=>i!==j))}><X size={16}/></button>}</div>)}<button className="text-button" type="button" onClick={()=>setLines([...lines,{item_id:'',quantity:1,rate:0}])}><Plus size={16}/>Add line</button><div className="m-total"><span>Order total</span><strong>{money(total.toString())}</strong></div><Field label="Notes / terms"><textarea name="notes" defaultValue={record?.notes}/></Field><div className="m-form-actions"><small>Saved as draft. {purchase?'Mark sent':'Confirm'} when ready.</small><button className="primary" disabled={busy||!items.length||!parties.length}>{busy?'Saving…':'Save draft'}</button></div></form>;
}
function MovementTable({kind,rows,data}:{kind:string;rows:Row[];data:Row}){const receipt=kind==='receipts';if(!rows.length)return <Empty text={receipt?'No goods receipts yet':'No dispatch notes yet'}/>;return <div className="m-table"><table><thead><tr><th>{receipt?'Receipt':'Dispatch note'}</th><th>Order</th><th>Date</th><th>Items and quantities</th><th/></tr></thead><tbody>{rows.map(r=>{const order=data[receipt?'purchase':'sales'].find((o:Row)=>o.id===r[receipt?'purchase_order_id':'sales_order_id']);return <tr key={r.id}><td><strong>{r.receipt_no||r.dispatch_no}</strong></td><td>{order?.po_no||order?.so_no}<small>{order?.party_snapshot.name}</small></td><td>{dateLabel(r.date)}</td><td>{r.lines.map((l:Row)=><small key={l.item_id}>{l.name} · {quantity(l.quantity)} {l.unit}</small>)}</td><td><PdfLink kind={receipt?'receipt':'dispatch'} id={r.id}/></td></tr>;})}</tbody></table></div>;}
function MovementForm({kind,data,busy,save}:{kind:string;data:Row;busy:boolean;save:(d:Row)=>void}){
 const receipt=kind==='receipts',orders=data[receipt?'purchase':'sales'].filter((o:Row)=>(receipt?['SENT','PARTIALLY_RECEIVED']:['CONFIRMED','PARTIALLY_DISPATCHED']).includes(o.status));
 const [selected,setSelected]=useState(''),[entered,setEntered]=useState<Row>({}),[submission]=useState(()=>crypto.randomUUID());
 const order=orders.find((o:Row)=>o.id===selected),lines=order?remaining(order,data[receipt?'receipts':'dispatches'],receipt?'purchase_order_id':'sales_order_id'):[];
 return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),id:submission,order_id:selected,lines:lines.filter((l:Row)=>Number(entered[l.item_id])>0).map((l:Row)=>({item_id:l.item_id,quantity:Number(entered[l.item_id])}))});}}><div className="m-form-grid"><Field label={receipt?'Purchase order':'Sales order'}><select required value={selected} onChange={e=>{setSelected(e.target.value);setEntered({});}}><option value="">Select an open order</option>{orders.map((o:Row)=><option key={o.id} value={o.id}>{o.po_no||o.so_no} · {o.party_snapshot.name}</option>)}</select></Field><Field label={receipt?'Receipt date':'Dispatch date'}><input name="date" type="date" min={order?.date} max={data.today} required defaultValue={data.today}/></Field></div>{!orders.length&&<div className="m-help">{receipt?'Create and mark a purchase order as sent first.':'Create and confirm a sales order first.'}</div>}{lines.length>0&&<div className="m-table m-form-table"><table><thead><tr><th>Item</th><th>Remaining</th>{!receipt&&<th>Available stock</th>}<th>{receipt?'Received now':'Dispatch now'}</th></tr></thead><tbody>{lines.filter((l:Row)=>l.remaining>0).map((l:Row)=><tr key={l.item_id}><td><strong>{l.name}</strong><small>{l.unit}</small></td><td>{quantity(l.remaining)}</td>{!receipt&&<td>{quantity(data.finished.find((f:Row)=>f.id===l.item_id)?.current_stock_qty)}</td>}<td><input aria-label={`${l.name} quantity`} type="number" min="0" max={l.remaining} step={l.unit==='pc'?'1':'0.001'} value={entered[l.item_id]||''} placeholder="0" onChange={e=>setEntered({...entered,[l.item_id]:e.target.value})}/></td></tr>)}</tbody></table></div>}<Field label="Notes / reference"><textarea name="notes" placeholder="Delivery reference, vehicle number or notes"/></Field><div className="m-form-actions"><small>Posted entries update stock and cannot be edited.</small><button className="primary" disabled={busy||!selected||!Object.values(entered).some(v=>Number(v)>0)}>{busy?'Posting…':receipt?'Post goods receipt':'Post dispatch'}</button></div></form>;
}
function OpeningForm({data,busy,save}:{data:Row;busy:boolean;save:(d:Row)=>void}){const [submission]=useState(()=>crypto.randomUUID()),eligible=data.finished.filter((f:Row)=>f.is_active&&!data.openings.some((o:Row)=>o.finished_good_id===f.id));return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),id:submission});}}><p className="m-help">Enter an existing, counted stock balance. This can be done only once per finished good and is permanently recorded with your user account and note.</p><div className="m-form-grid"><div className="m-span"><Field label="Finished good"><select name="finished_good_id" required><option value="">Select finished good</option>{eligible.map((f:Row)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field></div><Field label="Opening date"><input name="date" type="date" required max={data.today} defaultValue={data.today}/></Field><Field label="Counted quantity (pieces)"><input name="quantity" type="number" min="1" step="1" required/></Field><div className="m-span"><Field label="Audit note / count reference"><textarea name="notes" required minLength={3} placeholder="Physical count reference and reason for this opening balance"/></Field></div></div><div className="m-form-actions"><button className="primary" disabled={busy||!eligible.length}>{busy?'Posting…':'Post opening stock'}</button></div></form>;}
function InvoiceForm({data,busy,save}:{data:Row;busy:boolean;save:(d:Row)=>void}){const orders=data.sales.filter((o:Row)=>o.status==='DISPATCHED'),[selected,setSelected]=useState(''),[gst,setGst]=useState('18'),order=orders.find((o:Row)=>o.id===selected);const subtotal=new Decimal(order?.total_amount||0),tax=subtotal.mul(gst||0).div(100).toDecimalPlaces(2);return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),sales_order_id:selected,gst_percent:gst});}}><div className="m-form-grid"><div className="m-span"><Field label="Fully dispatched sales order"><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select sales order</option>{orders.map((o:Row)=><option value={o.id} key={o.id}>{o.so_no} · {o.party_snapshot.name}</option>)}</select></Field></div><Field label="Invoice date"><input name="date" type="date" required min={order?.date} max={data.today} defaultValue={data.today}/></Field><Field label="GST (%)"><input type="number" required min="0" max="100" step="0.01" value={gst} onChange={e=>setGst(e.target.value)}/></Field></div>{!orders.length&&<p className="m-help">Fully dispatch a sales order to make it available for invoicing.</p>}{order&&<><OrderLines lines={order.lines}/><div className="m-invoice-totals"><p>Subtotal <strong>{money(subtotal.toString())}</strong></p><p>GST ({gst}%) <strong>{money(tax.toString())}</strong></p><p>Total payable <strong>{money(subtotal.add(tax).toString())}</strong></p></div></>}<Field label="Sales terms / invoice notes"><textarea name="notes" placeholder="Payment or delivery terms for this sale"/></Field><div className="m-form-actions"><small>Issue once per order. The final invoice is locked.</small><button className="primary" disabled={busy||!selected}>{busy?'Issuing…':'Issue final sales invoice'}</button></div></form>;}
function OrderLines({lines}:{lines:Row[]}){return <div className="m-table m-form-table"><table><thead><tr><th>Item</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{lines.map(l=><tr key={l.item_id}><td><strong>{l.name}</strong></td><td>{quantity(l.quantity)} {l.unit}</td><td>{money(l.rate)}</td><td>{money(l.amount)}</td></tr>)}</tbody></table></div>;}
function OrderDetail({data,order,busy,cancel}:{data:Row;order:Row;busy:boolean;cancel:()=>void}){const purchase=order.orderKind==='purchase',docs=data[purchase?'receipts':'dispatches'],lines=remaining(order,docs,purchase?'purchase_order_id':'sales_order_id');return <><div className="m-detail-head"><div><h3>{order.party_snapshot.name}</h3><p>{dateLabel(order.date)}</p></div><Status value={order.status}/></div><OrderLines lines={order.lines}/><div className="m-total"><span>Order total</span><strong>{money(order.total_amount)}</strong></div><h3 className="m-form-section-title">Outstanding quantities</h3>{lines.map((l:Row)=><div className="m-outstanding" key={l.item_id}><span>{l.name}</span><strong>{quantity(l.remaining)} {l.unit}</strong></div>)}<p className="m-help">{order.notes}</p><div className="m-form-actions"><PdfLink kind={order.orderKind} id={order.id}/>{['DRAFT',purchase?'SENT':'CONFIRMED'].includes(order.status)&&<button className="secondary" disabled={busy} onClick={cancel}>Cancel order</button>}</div></>;}
