'use client';
import {useState} from 'react';
import Decimal from 'decimal.js';
type Row=Record<string,any>;
const qty=(v:unknown)=>Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:3});
const money=(v:unknown)=>Number(v||0).toLocaleString('en-IN',{style:'currency',currency:'INR'});
const activeOrders=(data:Row)=>data.workorders.filter((w:Row)=>['RELEASED','IN_PROGRESS'].includes(w.status));
export function ProductionTable({view,data,search,open,run,busy}:{view:string;data:Row;search:string;open:(kind:string,record?:Row)=>void;run:(action:string,data:Row,message?:string)=>unknown;busy:boolean}){
 const rows=data[view].filter((r:Row)=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 if(!rows.length)return <div className="m-empty"><h3>{view==='boms'?'Define the materials for your products':view==='workorders'?'Plan your first production batch':'No production posted yet'}</h3><p>{view==='boms'?'Add a BOM with raw-material quantities needed for one finished piece.':view==='workorders'?'Create a work order from an active BOM, then release it.':'Complete a released work order to consume materials and add finished stock.'}</p></div>;
 if(view==='boms')return <div className="m-table"><table><thead><tr><th>Finished good</th><th>Revision</th><th>Materials per piece</th><th>Status</th><th/></tr></thead><tbody>{rows.map((b:Row)=><tr key={b.id}><td><strong>{b.product_name}</strong><small>{b.notes}</small></td><td>v{b.revision}</td><td>{b.lines.map((l:Row)=><small key={l.item_id}>{l.name}: {qty(l.quantity)} {l.unit}</small>)}</td><td>{b.is_active?'Current':'Previous revision'}</td><td>{b.is_active&&<button className="text-button" onClick={()=>open('boms',b)}>New revision</button>}</td></tr>)}</tbody></table></div>;
 if(view==='workorders')return <div className="m-table"><table><thead><tr><th>Work order</th><th>Product / BOM</th><th>Dates</th><th>Progress</th><th>Status</th><th/></tr></thead><tbody>{rows.map((w:Row)=><tr key={w.id}><td><strong>{w.work_order_no}</strong><small>{w.notes}</small></td><td>{w.product_name}<small>BOM v{w.bom_snapshot.revision}</small></td><td>{w.date}<small>Due: {w.due_date||'Not set'}</small></td><td>{qty(w.completed_quantity)} / {qty(w.quantity)} pcs</td><td><span className="m-status">{w.status.replaceAll('_',' ')}</span></td><td><div className="m-row-actions"><button className="text-button" onClick={()=>open('workdetail',w)}>Materials</button>{w.status==='DRAFT'&&<button className="m-small-button" disabled={busy} onClick={()=>run('workorders/transition',{id:w.id,action:'release'},'Work order released. Stock changes only when production is posted.')}>Release</button>}{['RELEASED','IN_PROGRESS'].includes(w.status)&&<button className="m-small-button" onClick={()=>open('production',w)}>Record production</button>}{['DRAFT','RELEASED'].includes(w.status)&&<button className="text-button" disabled={busy} onClick={()=>open('cancelwork',w)}>Cancel</button>}</div></td></tr>)}</tbody></table></div>;
 return <div className="m-table"><table><thead><tr><th>Work order / date</th><th>Produced</th><th>Raw material consumed</th><th>Labour</th><th>Audit note</th></tr></thead><tbody>{rows.map((p:Row)=>{const w=data.workorders.find((w:Row)=>w.id===p.work_order_id);return <tr key={p.id}><td><strong>{w?.work_order_no}</strong><small>{p.date}</small></td><td>{qty(p.quantity)} pcs<small>{w?.product_name}</small></td><td>{p.consumption.map((l:Row)=><small key={l.item_id}>{l.name}: {qty(l.quantity)} {l.unit}{Number(l.wastage)>0?` (wastage ${qty(l.wastage)})`:''}</small>)}</td><td>{money(p.labour_cost)}</td><td>{p.notes}</td></tr>;})}</tbody></table></div>;
}
export function BomForm({data,record,busy,save}:{data:Row;record?:Row;busy:boolean;save:(d:Row)=>unknown}){
 const [lines,setLines]=useState<Row[]>(record?.lines||[{item_id:'',quantity:1}]);
 const raw=data.raw.filter((r:Row)=>r.is_active),products=data.finished.filter((r:Row)=>r.is_active);
 function update(index:number,patch:Row){setLines(lines.map((l,i)=>i===index?{...l,...patch}:l));}
 return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),lines:lines.map(l=>({item_id:l.item_id,quantity:l.quantity}))});}}><p className="m-help">Quantities below make one finished piece. Saving creates a new revision. Existing work orders retain their previous recipe.</p><label className="m-field">Finished good<select name="finished_good_id" required defaultValue={record?.finished_good_id||''}><option value="">Choose product</option>{products.map((p:Row)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><h3 className="m-form-section-title">Raw materials per finished piece</h3>{lines.map((l,i)=>{const unit=raw.find((r:Row)=>r.id===l.item_id)?.unit;return <div className="m-line" key={i}><label className="m-field">Raw material<select required value={l.item_id} onChange={e=>update(i,{item_id:e.target.value})}><option value="">Select raw material</option>{raw.map((r:Row)=><option key={r.id} value={r.id}>{r.name} ({r.unit})</option>)}</select></label><label className="m-field">Quantity ({unit||'unit'})<input type="number" required min={unit==='pc'?1:0.001} step={unit==='pc'?1:0.001} value={l.quantity} onChange={e=>update(i,{quantity:e.target.value})}/></label>{lines.length>1&&<button type="button" className="text-button" onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>Remove</button>}</div>;})}<button type="button" className="text-button" onClick={()=>setLines([...lines,{item_id:'',quantity:1}])}>+ Add material</button><label className="m-field">Revision notes<textarea name="notes" required placeholder="Recipe specification or reason for revision"/></label><div className="m-form-actions"><button className="primary" disabled={busy||!raw.length||!products.length}>{busy?'Saving…':'Save BOM revision'}</button></div></form>;
}
export function WorkOrderForm({data,busy,save}:{data:Row;busy:boolean;save:(d:Row)=>unknown}){
 const [bomId,setBom]=useState(''),[amount,setAmount]=useState(1),[submission]=useState(()=>crypto.randomUUID());const boms=data.boms.filter((b:Row)=>b.is_active&&data.finished.some((f:Row)=>f.id===b.finished_good_id&&f.is_active)),bom=boms.find((b:Row)=>b.id===bomId);
 return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),id:submission,bom_id:bomId,quantity:amount});}}><div className="m-form-grid"><label className="m-field m-span">Product / current BOM<select required value={bomId} onChange={e=>setBom(e.target.value)}><option value="">Choose BOM</option>{boms.map((b:Row)=><option key={b.id} value={b.id}>{b.product_name} · v{b.revision}</option>)}</select></label><label className="m-field">Planned good pieces<input type="number" min="1" max="10000000" step="1" required value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label className="m-field">Work-order date<input name="date" type="date" required max={data.today} defaultValue={data.today}/></label><label className="m-field">Due date (optional)<input name="due_date" type="date"/></label></div>{bom&&<Requirements lines={bom.lines} count={amount} data={data}/>}<p className="m-help">Material availability is checked again when posting production. Creating or releasing this order does not reserve stock.</p><label className="m-field">Batch / job notes<textarea name="notes"/></label><div className="m-form-actions"><button className="primary" disabled={busy||!bom}>{busy?'Saving…':'Create draft work order'}</button></div></form>;
}
export function Requirements({lines,count,data}:{lines:Row[];count:number;data:Row}){return <div className="m-table m-form-table"><table><thead><tr><th>Material</th><th>Required</th><th>Available now</th><th>Shortfall</th></tr></thead><tbody>{lines.map(l=>{const required=new Decimal(l.quantity).mul(count||0),available=new Decimal(data.raw.find((r:Row)=>r.id===l.item_id)?.current_stock_qty||0),short=Decimal.max(0,required.sub(available));return <tr key={l.item_id}><td>{l.name}</td><td>{qty(required)} {l.unit}</td><td>{qty(available)} {l.unit}</td><td>{short.gt(0)?<strong style={{color:'#b34336'}}>{qty(short)} {l.unit}</strong>:'Ready'}</td></tr>;})}</tbody></table></div>;}
export function ProductionForm({data,record,busy,save}:{data:Row;record?:Row;busy:boolean;save:(d:Row)=>unknown}){
 const orders=activeOrders(data),[selected,setSelected]=useState(record?.id||''),[count,setCount]=useState(1),[waste,setWaste]=useState<Row>({}),[submission]=useState(()=>crypto.randomUUID()),order=orders.find((w:Row)=>w.id===selected);
 return <form onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),id:submission,work_order_id:selected,quantity:count,wastage:order.bom_snapshot.lines.map((l:Row)=>({item_id:l.item_id,quantity:Number(waste[l.item_id]||0)}))});}}><div className="m-form-grid"><label className="m-field m-span">Released work order<select required value={selected} onChange={e=>{setSelected(e.target.value);setWaste({});setCount(1);}}><option value="">Choose work order</option>{orders.map((w:Row)=><option key={w.id} value={w.id}>{w.work_order_no} · {w.product_name} · {w.quantity-w.completed_quantity} remaining</option>)}</select></label><label className="m-field">Good pieces completed now<input type="number" required min="1" step="1" max={order?order.quantity-order.completed_quantity:10000000} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label className="m-field">Production date<input name="date" type="date" required min={order?.date} max={data.today} defaultValue={data.today}/></label></div>{order&&<><Requirements lines={order.bom_snapshot.lines} count={count} data={data}/><h3 className="m-form-section-title">Additional material wastage</h3><p className="m-help">Enter extra raw material consumed beyond the BOM requirement. This is deducted from stock too. Good pieces alone are added to finished stock.</p>{order.bom_snapshot.lines.map((l:Row)=><label key={l.item_id} className="m-field">{l.name} — extra waste ({l.unit})<input type="number" min="0" step={l.unit==='pc'?1:0.001} value={waste[l.item_id]||''} placeholder="0" onChange={e=>setWaste({...waste,[l.item_id]:e.target.value})}/></label>)}</>}<label className="m-field">Labour cost for this entry (₹)<input name="labour_cost" type="number" min="0" step="0.01" defaultValue="0" required/></label><label className="m-field">Batch / quality check / wastage note<textarea name="notes" required minLength={3}/></label><p className="m-help">Review before posting. This permanently records consumption and finished output together. Partial completion is supported.</p><div className="m-form-actions"><button className="primary" disabled={busy||!order}>{busy?'Posting…':'Post completed production'}</button></div></form>;
}
