'use client';
import {useState} from 'react';
import {validGstin} from './gst';
import {importGstText} from './gst-import';
export default function GstLookup(){
 const [message,setMessage]=useState(''),[challenge,setChallenge]=useState<{image:string;token:string;gstin:string}|null>(null),[captcha,setCaptcha]=useState(''),[busy,setBusy]=useState(false),[pasted,setPasted]=useState('');
 const number=(form:HTMLFormElement)=>{const input=form.elements.namedItem('gst_no') as HTMLInputElement;input.value=input.value.trim().toUpperCase();if(!validGstin(input.value))throw Error('Enter a valid GSTIN below first.');return input.value;};
 function apply(form:HTMLFormElement,d:Record<string,unknown>){for(const [key,value] of Object.entries(d)){const field=form.elements.namedItem(key) as HTMLInputElement|null;if(field&&typeof value==='string')field.value=value;}}
 async function load(form:HTMLFormElement){setBusy(true);setChallenge(null);setCaptcha('');try{const gstin=number(form),r=await fetch('/api/rental/gst?gstin='+gstin,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setChallenge({...d,gstin});setMessage('Enter the CAPTCHA below to fetch registered business details. No paid provider is used.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="gst-tools"><button className="secondary" type="button" disabled={busy} onClick={e=>void load(e.currentTarget.closest('form')!)}>{busy?'Contacting GST portal…':'Fetch GST details'}</button>{challenge&&<div className="form-section"><img src={challenge.image} alt="GST portal CAPTCHA. Enter its characters below." width={220} style={{display:'block',maxWidth:'100%',height:'auto'}}/><label className="field"><span>CAPTCHA characters</span><input value={captcha} autoComplete="off" maxLength={10} onChange={e=>setCaptcha(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault();}}/></label><button className="secondary" type="button" disabled={busy||captcha.trim().length<4} onClick={async e=>{const form=e.currentTarget.closest('form')!;setBusy(true);try{const gstin=number(form);if(gstin!==challenge.gstin)throw Error('GSTIN changed. Load a new CAPTCHA.');const r=await fetch('/api/rental/gst',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gstin,token:challenge.token,captcha:captcha.trim()})}),d=await r.json();if(!r.ok)throw Error(d.error);apply(form,d);setChallenge(null);setCaptcha('');setMessage('Details fetched. Registration status: '+d.registration_status+'. Review the profile before saving; confirm contact details and place of supply.');}catch(e){setMessage((e as Error).message+' Use Fetch GST details for a fresh CAPTCHA if needed.');}finally{setBusy(false);}}}>Verify CAPTCHA &amp; fill details</button></div>}<p role="status">{message||'Free direct GST portal lookup. Enter GSTIN below, then fetch and complete the CAPTCHA.'}</p><details className="form-section"><summary>Portal unavailable? Import its copied result</summary><a className="secondary" target="_blank" rel="noopener noreferrer" href="https://services.gst.gov.in/services/searchtp">Open official GST search</a><label className="field"><span>Paste the result including GSTIN and field labels</span><textarea rows={5} value={pasted} onChange={e=>setPasted(e.target.value)} maxLength={20000}/></label><button className="secondary" type="button" onClick={e=>{const form=e.currentTarget.closest('form')!;try{apply(form,importGstText(pasted,number(form)));setMessage('Copied details applied. Review before saving.');}catch(e){setMessage((e as Error).message);}}}>Apply copied details</button></details></section>;
}
