import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import ExcelJS from 'exceljs';
import {pool} from '@/lib/db';
import {materialGroups} from './material-ledger';
import {z} from 'zod';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
export async function materialExport(params:URLSearchParams){const d=z.object({customer:z.string().uuid(),start:date,end:date,item:z.union([z.string().uuid(),z.literal('')]).default(''),format:z.enum(['pdf','xlsx']).default('pdf')}).parse(Object.fromEntries(params));if(d.start>d.end)throw new Error('Choose a valid date range.');
 const c=(await pool.query('SELECT * FROM customers WHERE id=$1',[d.customer])).rows[0];if(!c)throw new Error('Customer not found.');const company=(await pool.query('SELECT * FROM company WHERE id=1')).rows[0];const items=(await pool.query('SELECT id,name FROM items ORDER BY name')).rows;const moves=(await pool.query('SELECT id,item_id,date,type,quantity,reference,created_at FROM movements WHERE customer_id=$1 AND date<=$2 ORDER BY date,created_at,id',[d.customer,d.end])).rows;const groups=materialGroups(items,moves,d.start,d.end,d.item);
 const headers=['Date','Vhty','Reference','Item Name','Issu Qty','Rcpt Qty','Pend.Qty'];const fmt=(s:string)=>s.slice(8,10)+'/'+s.slice(5,7)+'/'+s.slice(2,4);const rows:{values:(string|number)[];subtotal?:boolean}[]=[];
 for(const g of groups){rows.push({values:['Opening Balance','','',g.name,'','',g.opening]});for(const m of g.rows)rows.push({values:[fmt(m.date),m.type==='DISPATCH'?'Outw':'Inwr',m.reference||m.id.slice(0,8),g.name,m.type==='DISPATCH'?Number(m.quantity):'',m.type==='RETURN'?Number(m.quantity):'','']});rows.push({values:['','','','Sub Total',g.issued,g.received,g.pending],subtotal:true},{values:[]});}
 const totals=groups.reduce((t,g)=>({issued:t.issued+g.issued,received:t.received+g.received,pending:t.pending+g.pending}),{issued:0,received:0,pending:0});rows.push({values:['','','','Sub Total',totals.issued,totals.received,totals.pending],subtotal:true},{values:['Closing Balance','','',totals.pending.toFixed(2)+' DB','','','']});
 if(d.format==='xlsx'){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Material ledger');sheet.columns=[{width:16},{width:9},{width:18},{width:47},{width:14},{width:14},{width:14}];sheet.mergeCells('A1:G1');sheet.getCell('A1').value=company.name;sheet.getCell('A1').font={bold:true,size:17};sheet.getCell('A1').alignment={horizontal:'center'};sheet.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE6E6E6'}};
 const top=[`Statement Of: ${c.name}`,`Site Name: ${c.name}`,c.address,`Phone: ${c.mobile}`,`From: ${fmt(d.start)}     To: ${fmt(d.end)}`];top.forEach((t,i)=>{sheet.mergeCells(i+2,1,i+2,7);sheet.getCell(i+2,1).value=t;sheet.getCell(i+2,1).alignment={wrapText:true};sheet.getRow(i+2).height=i===2?36:22;});sheet.addRow(headers).font={bold:true};for(const row of rows){const r=sheet.addRow(row.values);r.height=Math.max(20,Math.ceil(String(row.values[3]||'').length/40)*14);r.getCell(4).alignment={wrapText:true};for(let i=5;i<=7;i++)r.getCell(i).numFmt='0.00';if(row.subtotal){r.font={bold:true};for(let i=5;i<=7;i++)r.getCell(i).border={top:{style:'thin'},bottom:{style:'thin'}};}}sheet.pageSetup={paperSize:1 as ExcelJS.PaperSize,orientation:'portrait',fitToPage:true,fitToWidth:1,fitToHeight:0,printTitlesRow:'1:7',margins:{left:.3,right:.3,top:.4,bottom:.4,header:.2,footer:.2}};sheet.views=[{state:'frozen',ySplit:7}];return {bytes:new Uint8Array(await book.xlsx.writeBuffer()),type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',extension:'xlsx'};}
 const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page:any,y=0;const xs=[34,85,118,171,394,462,525,592];const clean=(v:unknown)=>String(v??'').replace(/[^\x20-\x7e]/g,' ');function text(v:unknown,x:number,yy:number,size=8,strong=false){page.drawText(clean(v),{x,y:yy,size,font:strong?bold:font});}function newPage(){page=pdf.addPage([612,792]);page.drawRectangle({x:34,y:744,width:558,height:20,borderColor:rgb(0,0,0),borderWidth:1.2,color:rgb(.9,.9,.9)});const title=clean(company.name);text(title,Math.max(34,(626-bold.widthOfTextAtSize(title,13))/2),749,13,true);text('Statement Of: '+c.name,36,731);text('Site Name: '+c.name,36,717);const address=clean(c.address);for(let i=0;i<Math.min(address.length,210);i+=105)text(address.slice(i,i+105),36,701-(i/105)*12);text('Phone: '+c.mobile,36,677);text(`From: ${fmt(d.start)}       To: ${fmt(d.end)}`,36,663);y=647;headers.forEach((h,i)=>text(h,xs[i],y));page.drawLine({start:{x:32,y:y-5},end:{x:592,y:y-5},thickness:.5});y-=20;}
 newPage();for(const row of rows){const name=clean(row.values[3]||'');const chunks=name.match(/.{1,36}(?:\s|$)|.{1,36}/g)||[''];const height=Math.max(14,chunks.length*10+4);if(y-height<40)newPage();row.values.forEach((v,i)=>{if(i===3){chunks.forEach((c,n)=>text(c,row.subtotal?342:xs[i],y-n*10,8,!!row.subtotal));}else{const t=typeof v==='number'?v.toFixed(2):clean(v);text(t,i>=4?xs[i+1]-5-font.widthOfTextAtSize(t,8):xs[i],y,8,!!row.subtotal);}});if(row.subtotal){for(const yy of [y+11,y-height+3])page.drawLine({start:{x:394,y:yy},end:{x:592,y:yy},thickness:.6});}y-=height;}
 pdf.getPages().forEach((p,i)=>p.drawText(`${i+1} / ${pdf.getPageCount()}`,{x:535,y:20,size:7,font}));return {bytes:await pdf.save(),type:'application/pdf',extension:'pdf'};
}
