import nextEnv from '@next/env';
import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
nextEnv.loadEnvConfig(process.cwd());
const sourceUrl=process.env.DATABASE_URL!;
const admin=new pg.Client({connectionString:sourceUrl});await admin.connect();
const database='jyoti_test_'+randomUUID().replaceAll('-','');
await admin.query(`CREATE DATABASE "${database}"`);
const url=new URL(sourceUrl);url.pathname='/'+database;process.env.DATABASE_URL=url.toString();
const {pool}=await import('../src/lib/db');
try {
 for(const file of (await readdir('db')).filter(f=>/^\d+.*\.sql$/.test(f)).sort()) await pool.query(await readFile('db/'+file,'utf8'));
 await pool.query(`INSERT INTO company(id,name,unit1,unit2,mobile,email,website,bank_name,bank_account,bank_ifsc,terms) VALUES(1,'Jyoti Engineering & Jyoti Scaffold Pvt Ltd','Unit 1: Jamnagar, Gujarat 361010','Unit 2: Changodar, Ahmedabad, Gujarat 382213','8481000092 / 93 / 94 / 95','admin@jyotiscaffold.com','www.jyotiscaffolding.com','Jyoti Engineering','O72605501164','ICIC0000726','Test document only. Damage is charged at the original material price.')`);
 const operations=await import('../src/lib/service');
 const service=operations;
 const {makePdf,makeExcel}=await import('../src/lib/documents');
 const customer=await service.saveCustomer({name:'TEST - Rental validation',locking_days:10});
 const item=await service.saveItem({name:'Scaffolding pipe 06 mtr',material_value:1200,rate:3,effective_from:'2026-01-01'});
 await service.saveMovement({customer_id:customer.id,date:'2026-06-01',type:'DISPATCH',lines:[{item_id:item.id,quantity:100}]});
 await service.saveCustomer({id:customer.id,name:'TEST - Rental validation',locking_days:20});
 await service.saveMovement({customer_id:customer.id,date:'2026-06-05',type:'DISPATCH',lines:[{item_id:item.id,quantity:50}]});
 const ret=await service.saveMovement({customer_id:customer.id,date:'2026-06-06',type:'RETURN',lines:[{item_id:item.id,quantity:120,damaged_quantity:2}]});
 assert.deepEqual(ret.previews[0].deferred.map(a=>[a.quantity,a.billing_date]),[[100,'2026-06-11'],[20,'2026-06-25']]);
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM return_allocations')).rows[0].n,2);
 assert.equal(ret.previews[0].damage_total,'2400.00');
 await service.saveItem({id:item.id,name:'Scaffolding pipe 06 mtr',material_value:1500});
 const preview=await service.createInvoice({customer_id:customer.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:18},true) as any;
 assert.equal(preview.damage_total,'2400.00');
 assert.equal(preview.rental_total,'6540.00');
 assert.equal(preview.grand_total,'10549.20');
 const draft=await service.createInvoice({customer_id:customer.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:18}) as {id:string};
 await service.finalizeInvoice(draft.id);
 const invoice=(await pool.query('SELECT * FROM invoices WHERE id=$1',[draft.id])).rows[0];
 assert.equal(invoice.status,'FINAL');
 await assert.rejects(()=>pool.query("UPDATE invoices SET notes='tampered' WHERE id=$1",[draft.id]),/immutable/);
 await assert.rejects(()=>service.saveMovement({customer_id:customer.id,date:'2026-06-07',type:'DISPATCH',lines:[{item_id:item.id,quantity:1}]}),/already finalized/);
 await assert.rejects(()=>service.createInvoice({customer_id:customer.id,period_start:'2026-06-15',period_end:'2026-07-01',gst_percent:18}),/overlaps/);
 await assert.rejects(()=>service.saveItem({id:item.id,name:'Scaffolding pipe 06 mtr',material_value:1500,rate:4,effective_from:'2026-06-15'}),/finalized invoice/);
 const c2=await service.saveCustomer({name:'TEST - concurrent returns',locking_days:0});
 await service.saveMovement({customer_id:c2.id,date:'2026-06-01',type:'DISPATCH',lines:[{item_id:item.id,quantity:10}]});
 const attempts=await Promise.allSettled([1,2].map(()=>service.saveMovement({customer_id:c2.id,date:'2026-06-02',type:'RETURN',lines:[{item_id:item.id,quantity:7}]})));
 assert.equal(attempts.filter(a=>a.status==='fulfilled').length,1);
 assert.equal(attempts.filter(a=>a.status==='rejected').length,1);
 const before=(await pool.query('SELECT count(*)::int AS n FROM movements')).rows[0].n;
 const item2=await service.saveItem({name:'Fix Clamp Forged',material_value:98,rate:0.5,effective_from:'2026-01-01'});
 await assert.rejects(()=>service.saveMovement({customer_id:c2.id,date:'2026-06-03',type:'RETURN',lines:[{item_id:item.id,quantity:1},{item_id:item2.id,quantity:1}]}),/only 0/);
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM movements')).rows[0].n,before);
 const stale=await service.createInvoice({customer_id:c2.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:0}) as {id:string};
 await service.saveMovement({customer_id:c2.id,date:'2026-06-04',type:'DISPATCH',lines:[{item_id:item.id,quantity:2}]});
 await assert.rejects(()=>service.finalizeInvoice(stale.id),/Source data changed/);
 await service.updateInvoice(stale.id,{customer_id:c2.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:5,notes:'Reviewed and updated draft'});
 await service.finalizeInvoice(stale.id);
 assert.equal((await pool.query('SELECT notes FROM invoices WHERE id=$1',[stale.id])).rows[0].notes,'Reviewed and updated draft');
 await assert.rejects(()=>service.updateInvoice(stale.id,{}),/locked/);
 const quote=await service.saveQuotation({customer_id:customer.id,date:'2026-06-01',deposit:10000,terms:'Transport in customer scope.',lines:[{item_id:item.id,quantity:100,rate:3}]});
 assert.equal((await pool.query('SELECT snapshot FROM quotations WHERE id=$1',[quote.id])).rows[0].snapshot.monthly_total,'9000.00');
 const live=await service.state();assert.equal(live.balances.find(b=>b.customer_id===customer.id)?.physical,30);
 // Single delivery date, customer-specific rates and original return billing.
 const customerA=await service.saveCustomer({name:'TEST - agreed rate A',locking_days:10});
 const customerB=await service.saveCustomer({name:'TEST - standard rate B',locking_days:10});
 await service.saveMovement({customer_id:customerA.id,date:'2026-06-01',type:'DISPATCH',lines:[{item_id:item.id,quantity:100,rental_rate:2.5}]});
 await service.saveMovement({customer_id:customerB.id,date:'2026-06-01',type:'DISPATCH',lines:[{item_id:item.id,quantity:100}]});
 const revised=await service.saveMovement({customer_id:customerA.id,date:'2026-06-15',type:'RETURN',lines:[{item_id:item.id,quantity:30}]});
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM movements WHERE customer_id=$1 AND type=\'DISPATCH\'',[customerA.id])).rows[0].n,1);
 const quoteA=await service.createInvoice({customer_id:customerA.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:0},true) as any;
 const quoteB=await service.createInvoice({customer_id:customerB.id,period_start:'2026-06-01',period_end:'2026-06-30',gst_percent:0},true) as any;
 assert.equal(quoteA.rental_total,'6300.00');assert.equal(quoteB.rental_total,'9000.00');
 const early=await service.saveMovement({customer_id:customerB.id,date:'2026-06-05',type:'RETURN',lines:[{item_id:item.id,quantity:30}]});
 assert.equal(early.previews[0].after,70);assert.equal(early.previews[0].deferred[0].quantity,30);
 const repeat=await service.saveMovement({customer_id:customerA.id,date:'2026-06-16',type:'RETURN',lines:[{item_id:item.id,quantity:20}]});
 const moved=await service.state();assert.equal(moved.balances.find(b=>b.customer_id===customerA.id)?.physical,50);
 assert.equal(revised.previews[0].after,70);
 assert.equal(repeat.previews[0].after,50);
 assert.equal(repeat.previews[0].deferred.length,0);
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM rental_periods')).rows[0].n,0);
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM movements WHERE end_date IS NOT NULL')).rows[0].n,0);
 assert.equal('periods' in moved,false);
 const unchanged=(await pool.query('SELECT snapshot FROM invoices WHERE id=$1',[draft.id])).rows[0].snapshot;
 assert.deepEqual(unchanged,invoice.snapshot);
 console.log('PASS: single delivery date, saved customer-specific rates, no end dates or auto-created dispatch periods, original lock retained, no duplicate stock, customer rate isolation, unchanged finalized invoices.');
 await mkdir('test-results',{recursive:true});
 const pdf=await makePdf(invoice);assert.equal(Buffer.from(pdf).subarray(0,4).toString(),'%PDF');await writeFile('test-results/sample-invoice.pdf',pdf);
 const bigInvoice={...invoice,snapshot:{...invoice.snapshot,lines:Array.from({length:8},()=>invoice.snapshot.lines).flat()}};
 await writeFile('test-results/multipage-invoice.pdf',await makePdf(bigInvoice));
 await writeFile('test-results/sample-quotation.pdf',await makePdf((await pool.query('SELECT * FROM quotations WHERE id=$1',[quote.id])).rows[0],true));
 const excel=await makeExcel('ledger',customer.id);assert.equal(Buffer.from(excel).subarray(0,2).toString(),'PK');await writeFile('test-results/sample-ledger.xlsx',Buffer.from(excel));
 await writeFile('test-results/sample-invoices.xlsx',Buffer.from(await makeExcel('invoices')));
 console.log('PASS: PostgreSQL persistence, FIFO allocations, preserved lock dates, saved damage prices, exact totals, immutable final invoices, overlap/backdate protection, concurrent over-return prevention, atomic multi-item rollback, stale draft rejection, quotation, dashboard, PDF and Excel exports. Test database will be removed.');
}finally {await pool.end();await admin.query(`DROP DATABASE "${database}" WITH (FORCE)`);await admin.end();}
