import EmbeddedPostgres from 'embedded-postgres';
import { existsSync } from 'node:fs';
import path from 'node:path';
const directory=path.resolve('.postgres');
const pg=new EmbeddedPostgres({databaseDir:directory,user:'jyoti',password:'jyoti_local_only',port:54329,persistent:true,authMethod:'scram-sha-256',postgresFlags:['-h','127.0.0.1'],onLog:()=>{},onError:console.error});
if(!existsSync(path.join(directory,'PG_VERSION'))) await pg.initialise();
await pg.start();
const client=pg.getPgClient();await client.connect();
if(!(await client.query("SELECT 1 FROM pg_database WHERE datname='jyoti_rental'")).rowCount) await client.query('CREATE DATABASE jyoti_rental');
await client.end();
console.log('PostgreSQL is ready on 127.0.0.1:54329. Data persists in .postgres/. Keep this terminal running.');
const stop=async()=>{await pg.stop();process.exit(0);};
process.on('SIGINT',stop);process.on('SIGTERM',stop);
setInterval(()=>{},60000);
